repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.0"
    hooks:
      - id: ruff-format
  - repo: https://github.com/PyCQA/isort
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: local
    hooks:
      # shoutout to https://github.com/RobertCraigie/pyright-python
      - id: pyright
        name: pyright
        description: "Python command line wrapper for pyright, a static type checker"
        entry: basedpyright
        language: python
        types_or: [python]
        require_serial: true
        additional_dependencies:
          - basedpyright>=1.23.2
          - pytest>=8.3.4
        minimum_pre_commit_version: "2.9.2"
        fail_fast: true
      - id: pytest
        name: pytest-doctest
        entry: pytest --doctest-modules
        description: "Doctesting with pytest"
        language: python
        types_or: [python]
        pass_filenames: false
        additional_dependencies:
          - "pytest>=8.3.4"
      - id: pytest
        name: pytest
        entry: pytest
        description: "Run Python tests with Pytest"
        language: python
        types_or: [python]
        pass_filenames: false
        additional_dependencies:
          - "pytest>=8.3.4"
