"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any

def is_case(func: Callable[..., Any]) -> bool:
    """
    Determines if a function is marked as a 'case' using pytest.

    :param func: A function to check for the 'case' mark.
    :return: True if the function is marked with 'case', False otherwise.
    """
    ...

def validate_case_inputs(
    wrapped_func: Callable[..., Any], case_args: tuple[Any], case_kwargs: dict[str, Any]
) -> None:
    """
    Validate the input function for compatibility with case arguments.
    """
    ...
