"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any

def get_func_param_names(func: Callable[..., Any]) -> tuple[str, ...]:
    """
    Extracts the names of positional parameters from the given function.

    :param func: A callable to analyze.
    :return: A tuple of strings where each string is the name of a positional parameter.
    """
    ...

def get_func_optional_params(func: Callable[..., Any]) -> dict[str, Any]:
    """
    Extracts optional parameters from the given function.

    :param func: A callable to analyze.
    :return: A dictionary where the keys are the names of optional
        parameters and the values are their default values.
    """
    ...
