"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Iterable, Sequence
from typing import Any, overload

from _pytest.mark import ParameterSet
from pytest_case.types import UnwrappedFunc

__all__ = ["case"]

@overload
def case(cases_generator: Iterable[Any]) -> Callable[..., Any]: ...
@overload
def case(name: str, *args: Any, **kwargs: Any) -> Callable[..., Any]: ...
def wrap_func(
    argnames: Sequence[str], param_sets: list[ParameterSet], defaults: dict[str, Any]
) -> Callable[..., Callable[..., Any]]:
    """
    Wraps a function with `pytest.mark.case` and `pytest.mark.parametrize`.
    Should be unwrapped manually if another case is applied
    """
    ...

def unwrap_func(func: Callable[..., Any]) -> UnwrappedFunc:
    """
    Unwraps a case function into its original function and its pytest-case components.
    """
    ...

def case(
    name_or_gen: str | Iterable[Any], *args: Any, **kwargs: Any
) -> Callable[..., Any]:
    """
    Decorator to define test cases for pytest.
    """
    ...
