"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

import pytest
from _pytest.mark import ParameterSet

@dataclass
class UnwrappedFunc:
    unwrapped_func: Callable[[Any], Any]
    func_markers: list[pytest.MarkDecorator]
    argnames: tuple[str]
    argvalues: list[ParameterSet]
    defaults: dict[str, Any]
    ...
